### ISSUE TITLE
Clear line for readme

### ISSUE THREAD

**Issue by dmadisetti** [sioodmy/nixdots#10]
Your readme formatting gets a little weird on small screens. You can use a clear to format nicely: https://gist.github.com/DavidWells/7d2e0e1bc78f4ac59a123ddf8b74932d?permalink_comment_id=3456611#gistcomment-3456611

**Comment by sioodmy** [comment]
So, I added `<br clear="left"/>` to readme

Is it now ok?

**Comment by dmadisetti** [comment]
Yeah, it was just a suggestion. I think it looks great
